
services:
  my-app:
    build: .
    #image: .
    #docker-hub-user/image-name:image-tag
    ports:
     - 3000:3000
    environment:
     - MONGO_DB_USERNAME=${db_username}
     - MONGO_DB_PWD=${db_password}
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=${db_username}
     - MONGO_INITDB_ROOT_PASSWORD=${db_password}
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=${db_username}
     - ME_CONFIG_MONGODB_ADMINPASSWORD=${db_password}
     - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
     - "mongodb"
 
